import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./_components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "./_components/Sidebar";
import QueryProvider from "@/lib/query-provider";
import { auth } from "@clerk/nextjs/server";
import { db } from "@/lib/db";
import { ensureUserExists } from "@/actions/user";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	await ensureUserExists();

	return (
		<html lang="en" className="h-full" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-full overflow-hidden dark:bg-neutral-950`}
				suppressHydrationWarning
			>
				<ClerkProvider>
					<QueryProvider>
						<ThemeProvider
							attribute="class"
							defaultTheme="system"
							enableSystem
							disableTransitionOnChange
						>
							<Navbar />
							<main className="flex h-full">
								<Sidebar />
								<div className="flex-1 overflow-y-auto">
									{children}
								</div>
							</main>
						</ThemeProvider>
					</QueryProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
